export const INVOICES = "INVOICES";
export const INVOICE_INFO = "INVOICE_INFO";
export const INVOICE_ITEMS = "INVOICE_ITEMS";
export const INVOICE_COLLECTION = "INVOICE_COLLECTION";
export const INVOICE_OPTIONS = "INVOICE_OPTIONS";
