export const PURCHASES = "PURCHASES";
export const PURCHASES_INFO = "PURCHASES_INFO";
export const PURCHASES_ITEMS = "PURCHASES_ITEMS";
export const PURCHASES_PAYMENTS = "PURCHASES_PAYMENTS";
export const PURCHASES_OPTIONS = "PURCHASES_OPTIONS";
