export const PROJECTS = "PROJECTS";
export const PROJECTS_INFO = "PROJECTS_INFO";
export const PROJECTS_ITEMS = "PROJECTS_ITEMS";
// export const INVOICE_COLLECTION = "INVOICE_COLLECTION";
export const PROJECTS_OPTIONS = "PROJECTS_OPTIONS";
