export const SUPER_ADMIN = "SUPER_ADMIN";
export const ORGANIZATION_ADMIN = "ORGANIZATION_ADMIN";
export const ORGANIZATION_USER = "ORGANIZATION_USER";
export const ORGANIZATION_APPROVER = "ORGANIZATION_APPROVER";
